language: node_js
node_js:
  - '6.4.0'
notifications:
  email: false
before_install:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm install request;
      npm run update-package;
    fi
env:
  global:
    - secure: bBjEcbBAQZrgDOaw4yJo01zY3gFcR45tIO9KA8EPw2ZfYLotuUqJz22W0Eok1FD6xh3Lvdhv/2Ld5jpzeBlz3FZSn/6Ql2wPQviTATJj6vCouSXDvZMn3eG133jKmSo51ZHyGCk6OBAViTWcPrdNKomvemu5Dloy6Ga8RhGMY4U=
    - MERGE_TOKEN=872c194d635f08bfda7c4805e70f082f152be65b
    - SENDGRID_USERNAME=azai91
    - secure: KnpXv5UH8SgxMWk5LmwrtOAdUTc1JWBXZAM93eSa/jT+Eyk99B2fltbj6JXUcstDgx/cyveCNTnr6uRekR/qjPjV9QBY/NVb7ChSpISOro0H34POKSuw2Cyq8rWsclNc+ElwRDdzQ5ZD8BB06PakQXc13ETBmpdENlABX8CrBVc=
    - secure: hXCY0VVWcZS6kNjHGUboYQYsXc7e7mBwKaYiMCsRIM436Ap0fsBfJHere7wH34nyuMlx4/HfY6ZQEbFy4sWqGCDr32DlBTR0COYPgLgeopfTo+xNm8ivJ2pbHKmkMX+Z/GKuLDaM4zOKQYn3dNPeLlyL5faEz2RHJjlkM+1I5zg=
    - secure: hN2evUWb2QJkCV1pluA2fi8wTphuA3Untmp0fcDPw7wYi9MhILp95aIhA7wcM+NlLR/Pp2Wx9ByocmM+DJavzmRTtW8J1xzbTWhKKKVaWeBnf24yeGdCT1+MCyWEZontZlp80D+AOPlvvXNBe0f8B5fhJumnqqB0a5vPKRk8GvA=
script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm run get-test-utils && npm run test ; npm run lint ; npm run report;
    else
      npm run merge;
    fi
